spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529979837228-sn0tgnhjk5lg8sipgafbb0ppo4de33l5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email